<a href="https://colab.research.google.com/github/rex17/Machine-Learning-Practice/blob/master/Housing_Price_LinearRegr_with_Multivariable_MSE_0_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn import linear_model
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats

import statsmodels.api as sm

import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

print("import success")

import success


In [5]:

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving test.csv to test.csv
User uploaded file "test.csv" with length 451405 bytes


In [0]:
# importing data
housing_df = pd.read_csv('housing_df_cleaned.csv')
test_df = pd.read_csv('test.csv')

In [7]:
housing_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'Street', 'LotShape',
       'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood',
       'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageCars', 'GarageArea',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [14]:
housing_df.head()

Id  MSSubClass MSZoning  LotArea Street LotShape LandContour Utilities  \
0   1          60       RL     8450   Pave      Reg         Lvl    AllPub   
1   2          20       RL     9600   Pave      Reg         Lvl    AllPub   
2   3          60       RL    11250   Pave      IR1         Lvl    AllPub   
3   4          70       RL     9550   Pave      IR1         Lvl    AllPub   
4   5          60       RL    14260   Pave      IR1         Lvl    AllPub   

  LotConfig LandSlope    ...    EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0    Inside       Gtl    ...                0         0           0        0   
1       FR2       Gtl    ...                0         0           0        0   
2    Inside       Gtl    ...                0         0           0        0   
3    Corner       Gtl    ...              272         0           0        0   
4       FR2       Gtl    ...                0         0           0        0   

  MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0       0       2    2008        WD         Normal    208500  
1       0       5    2007        WD         Normal    181500  
2       0       9    2008        WD         Normal    223500  
3       0       2    2006        WD        Abnorml    140000  
4       0      12    2008        WD         Normal    250000  

[5 rows x 63 columns]

In [8]:
housing_df.shape

(1459, 63)

In [46]:
sale_price = np.array(housing_df["SalePrice"])
overall_qual = np.array(housing_df["OverallQual"])
year_built = np.array(housing_df["YearBuilt"])
total_bsmt_sf = np.array(housing_df["TotalBsmtSF"])
gr_liv_area = np.array(housing_df["GrLivArea"])
first_flr_sf = np.array(housing_df["1stFlrSF"])
#garage_yr_built = np.array(housing_df["GarageYrBlt"])
garage_cars = np.array(housing_df["GarageCars"])
garage_area = np.array(housing_df["GarageArea"])


print(sale_price)
print(overall_qual)
print(year_built)
print(total_bsmt_sf)
print(gr_liv_area)
print(first_flr_sf)
#print(garage_yr_built)
print(garage_cars)
print(garage_area)

[208500 181500 223500 ... 266500 142125 147500]
[7 6 7 ... 7 5 5]
[2003 1976 2001 ... 1941 1950 1965]
[ 856 1262  920 ... 1152 1078 1256]
[1710 1262 1786 ... 2340 1078 1256]
[ 856 1262  920 ... 1188 1078 1256]
[2 2 2 ... 1 1 1]
[548 460 608 ... 252 240 276]


In [0]:
#X = [list(overall_qual), list(total_bsmt_sf), list(gr_liv_area), list(first_flr_sf), list(garage_area)]
X = [list(total_bsmt_sf), list(gr_liv_area), list(first_flr_sf), list(garage_area)]

In [81]:
multi_regr = linear_model.LinearRegression()

multi_regr.fit(np.array(X).transpose(), sale_price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [0]:
overall_qual_test = np.array(test_df["OverallQual"])
year_built_test = np.array(test_df["YearBuilt"])
total_bsmt_sf_test = np.array(test_df["TotalBsmtSF"])
gr_liv_area_test = np.array(test_df["GrLivArea"])
first_flr_sf_test = np.array(test_df["1stFlrSF"])
garage_cars_test = np.array(test_df["GarageCars"])
garage_area_test = np.array(test_df["GarageArea"])

total_bsmt_sf_test = pd.DataFrame(total_bsmt_sf_test).fillna(method='pad')
total_bsmt_sf_test = np.mat(total_bsmt_sf_test)

garage_area_test = pd.DataFrame(garage_area_test).fillna(method='pad')
garage_area_test = np.mat(garage_area_test)

#X_test = [list(overall_qual_test), list(total_bsmt_sf_test), list(gr_liv_area_test), list(first_flr_sf_test), list(garage_area_test)]
X_test = [list(total_bsmt_sf_test), list(gr_liv_area_test), list(first_flr_sf_test), list(garage_area_test)]


In [90]:
np.sum(np.isnan(X_test[1]))

0

In [0]:
predictions = multi_regr.predict(np.array(X_test).transpose())

In [85]:
len(predictions)

1459

In [89]:
multi_regr.intercept_

-22527.93210228553

In [86]:
submission_df = pd.DataFrame(test_df['Id'],columns=['Id','SalePrice'])
submission_df["SalePrice"] = predictions
submission_df = submission_df[["Id","SalePrice"]]
submission_df.shape

(1459, 2)

In [87]:
submission_df.head()

Id      SalePrice
0  1461  156790.026568
1  1462  164495.175199
2  1463  184568.907005
3  1464  181479.816771
4  1465  178947.628199

In [0]:
submission_df.to_csv("ss_submission_lmMv4.csv", index = False)