<a href="https://colab.research.google.com/github/rex17/Machine-Learning-Practice/blob/master/Housing_Price_LinearRegr_with_Multivariable_MSE_0_23775.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import math


from sklearn import linear_model
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats

import statsmodels.api as sm

import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

print("import success")

/usr/local/lib/python3.6/dist-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


import success


In [2]:

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving housing_df_cleaned.csv to housing_df_cleaned.csv
Saving test.csv to test.csv
User uploaded file "housing_df_cleaned.csv" with length 363604 bytes
User uploaded file "test.csv" with length 451405 bytes


In [0]:
# importing data
housing_df = pd.read_csv('housing_df_cleaned.csv')
test_df = pd.read_csv('test.csv')

In [4]:
housing_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'Street', 'LotShape',
       'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood',
       'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageCars', 'GarageArea',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [5]:
housing_df.head()

Id  MSSubClass MSZoning  LotArea Street LotShape LandContour Utilities  \
0   1          60       RL     8450   Pave      Reg         Lvl    AllPub   
1   2          20       RL     9600   Pave      Reg         Lvl    AllPub   
2   3          60       RL    11250   Pave      IR1         Lvl    AllPub   
3   4          70       RL     9550   Pave      IR1         Lvl    AllPub   
4   5          60       RL    14260   Pave      IR1         Lvl    AllPub   

  LotConfig LandSlope    ...    EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0    Inside       Gtl    ...                0         0           0        0   
1       FR2       Gtl    ...                0         0           0        0   
2    Inside       Gtl    ...                0         0           0        0   
3    Corner       Gtl    ...              272         0           0        0   
4       FR2       Gtl    ...                0         0           0        0   

  MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0       0       2    2008        WD         Normal    208500  
1       0       5    2007        WD         Normal    181500  
2       0       9    2008        WD         Normal    223500  
3       0       2    2006        WD        Abnorml    140000  
4       0      12    2008        WD         Normal    250000  

[5 rows x 63 columns]

In [6]:
housing_df.shape

(1459, 63)

In [7]:
sale_price = np.asarray(housing_df["SalePrice"])
overall_qual = np.asarray(housing_df["OverallQual"])
year_built = np.asarray(housing_df["YearBuilt"])
total_bsmt_sf = np.asarray(housing_df["TotalBsmtSF"])
gr_liv_area = np.asarray(housing_df["GrLivArea"])
first_flr_sf = np.asarray(housing_df["1stFlrSF"])
#garage_yr_built = np.asarray(housing_df["GarageYrBlt"])
garage_cars = np.asarray(housing_df["GarageCars"])
garage_area = np.asarray(housing_df["GarageArea"])
lot_area = np.asarray(housing_df["LotArea"])
wood_deck_sf = np.asarray(housing_df["WoodDeckSF"])


print(sale_price)
print(overall_qual)
print(year_built)
print(total_bsmt_sf)
print(gr_liv_area)
print(first_flr_sf)
#print(garage_yr_built)
print(garage_cars)
print(garage_area)
print(lot_area)
print(wood_deck_sf)


[208500 181500 223500 ... 266500 142125 147500]
[7 6 7 ... 7 5 5]
[2003 1976 2001 ... 1941 1950 1965]
[ 856 1262  920 ... 1152 1078 1256]
[1710 1262 1786 ... 2340 1078 1256]
[ 856 1262  920 ... 1188 1078 1256]
[2 2 2 ... 1 1 1]
[548 460 608 ... 252 240 276]
[ 8450  9600 11250 ...  9042  9717  9937]
[  0 298   0 ...   0 366 736]


In [8]:
#X = [list(overall_qual), list(total_bsmt_sf), list(gr_liv_area), list(first_flr_sf), list(garage_area)]

X = [list(total_bsmt_sf), list(gr_liv_area), list(first_flr_sf), list(garage_area),list(lot_area),list(wood_deck_sf)]

len(X)

6

**MultiRegression Model Training** with 6 features 

In [10]:
multi_regr = linear_model.LinearRegression()

multi_regr.fit(np.array(X).transpose(), sale_price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [0]:
overall_qual_test = np.asarray(test_df["OverallQual"])
year_built_test = np.asarray(test_df["YearBuilt"])
total_bsmt_sf_test = np.asarray(test_df["TotalBsmtSF"])
gr_liv_area_test = np.asarray(test_df["GrLivArea"])
first_flr_sf_test = np.asarray(test_df["1stFlrSF"])
garage_cars_test = np.asarray(test_df["GarageCars"])
garage_area_test = np.asarray(test_df["GarageArea"])
lot_area_test = np.asarray(test_df["LotArea"])
wood_deck_sf_test = np.asarray(test_df["WoodDeckSF"])


# total_bsmt_sf_test = pd.DataFrame(total_bsmt_sf_test).fillna(method='pad')
# total_bsmt_sf_test = np.mat(total_bsmt_sf_test)

# garage_area_test = pd.DataFrame(garage_area_test).fillna(method='pad')
# garage_area_test = np.mat(garage_area_test)

#X_test = [list(overall_qual_test), list(total_bsmt_sf_test), list(gr_liv_area_test), list(first_flr_sf_test), list(garage_area_test)]
X_test = [list(total_bsmt_sf_test), list(gr_liv_area_test), list(first_flr_sf_test), list(garage_area_test),list(lot_area_test),list(wood_deck_sf_test)]


In [79]:
predictions = multi_regr.predict(np.array(X_test).transpose())

ValueError: ignored

In [23]:
multi_regr.intercept_

-21100.716759288043

In [24]:
multi_regr.coef_

array([ 51.99801988,  67.59935802,  -8.7148502 , 100.49663744,
         0.15319379,  58.97985622])

**Gradient descent on multifeature regression to optimize the theta**

In [0]:
def hypothesis(x,h_theta):
	return np.dot(np.transpose(h_theta),x)

def gradientDescent(x, y, gd_theta, m, alpha, iterations=10):
  for iteration in range(iterations):
    for j in range(len(gd_theta)):
      gradient = 0
      print(gd_theta)
      for i in range(m):
        gradient += (hypothesis(x[i], gd_theta) - y[i]) * x[i][j]
      gradient *= 1/m
      gd_theta[j] = gd_theta[j] - (alpha * gradient)
      if(np.all(np.absolute(gradient) <= 1e-5)):
        return gd_theta
  return gd_theta

In [71]:
#for gradient descent
X_gd = np.asarray([[totalbsmtsf, grlivarea, firstflrsf,garagearea,lotarea,wooddecksf] for totalbsmtsf, grlivarea, firstflrsf,garagearea,lotarea,wooddecksf in zip(total_bsmt_sf, gr_liv_area, first_flr_sf,garage_area,lot_area,wood_deck_sf)])
X_gd

array([[  856,  1710,   856,   548,  8450,     0],
       [ 1262,  1262,  1262,   460,  9600,   298],
       [  920,  1786,   920,   608, 11250,     0],
       ...,
       [ 1152,  2340,  1188,   252,  9042,     0],
       [ 1078,  1078,  1078,   240,  9717,   366],
       [ 1256,  1256,  1256,   276,  9937,   736]])

In [72]:
X_gd_test = np.asarray([[totalbsmtsf_test, grlivarea_test, firstflrsf_test,garagearea_test,lotarea_test,wooddecksf_test] for totalbsmtsf_test, grlivarea_test, firstflrsf_test,garagearea_test,lotarea_test,wooddecksf_test in zip(total_bsmt_sf_test, gr_liv_area_test, first_flr_sf_test, garage_area_test ,lot_area_test,wood_deck_sf_test)])
X_gd_test

array([[  882.,   896.,   896.,   730., 11622.,   140.],
       [ 1329.,  1329.,  1329.,   312., 14267.,   393.],
       [  928.,  1629.,   928.,   482., 13830.,   212.],
       ...,
       [ 1224.,  1224.,  1224.,   576., 20000.,   474.],
       [  912.,   970.,   970.,     0., 10441.,    80.],
       [  996.,  2000.,   996.,   650.,  9627.,   190.]])

In [0]:
X_gd = X_gd.astype(np.float)

In [74]:
X_gd

array([[  856.,  1710.,   856.,   548.,  8450.,     0.],
       [ 1262.,  1262.,  1262.,   460.,  9600.,   298.],
       [  920.,  1786.,   920.,   608., 11250.,     0.],
       ...,
       [ 1152.,  2340.,  1188.,   252.,  9042.,     0.],
       [ 1078.,  1078.,  1078.,   240.,  9717.,   366.],
       [ 1256.,  1256.,  1256.,   276.,  9937.,   736.]])

In [75]:
np.sum(np.isnan(X_gd))

0

In [78]:
multi_regr.coef_

array([-2.19705496e+170,  3.72100891e+172, -6.95591262e+174,
        4.07931118e+176, -2.09403138e+179,  2.52513290e+181])

In [76]:
initial_theta = multi_regr.coef_
initial_theta

array([-2.19705496e+170,  3.72100891e+172, -6.95591262e+174,
        4.07931118e+176, -2.09403138e+179,  2.52513290e+181])

In [33]:
np.dot( np.transpose(initial_theta),X_gd[1] )

205208.8607730695

In [36]:
alpha = 0.0001
alpha

0.0001

In [80]:
optimized_theta = gradientDescent(X_gd, sale_price, initial_theta, len(sale_price), alpha,10)
optimized_theta

[-2.19705496e+170  3.72100891e+172 -6.95591262e+174  4.07931118e+176
 -2.09403138e+179  2.52513290e+181]
[-2.70939350e+181  3.72100891e+172 -6.95591262e+174  4.07931118e+176
 -2.09403138e+179  2.52513290e+181]
[-2.70939350e+181  4.58872334e+183 -6.95591262e+174  4.07931118e+176
 -2.09403138e+179  2.52513290e+181]
[-2.70939350e+181  4.58872334e+183 -8.57798499e+185  4.07931118e+176
 -2.09403138e+179  2.52513290e+181]
[-2.70939350e+181  4.58872334e+183 -8.57798499e+185  5.03057930e+187
 -2.09403138e+179  2.52513290e+181]
[-2.70939350e+181  4.58872334e+183 -8.57798499e+185  5.03057930e+187
 -2.58234552e+190  2.52513290e+181]
[-2.70939350e+181  4.58872334e+183 -8.57798499e+185  5.03057930e+187
 -2.58234552e+190  3.11397703e+192]
[-3.34120598e+192  4.58872334e+183 -8.57798499e+185  5.03057930e+187
 -2.58234552e+190  3.11397703e+192]
[-3.34120598e+192  5.65878299e+194 -8.57798499e+185  5.03057930e+187
 -2.58234552e+190  3.11397703e+192]
[-3.34120598e+192  5.65878299e+194 -1.05783138e+197  5.

array([-1.78711527e+281,  3.02672076e+283, -5.65803675e+285,
        3.31816884e+287, -1.70331445e+290,  2.05397847e+292])

In [81]:
optimized_predictions = X_gd_test.dot(optimized_theta)
optimized_predictions

array([ 8.96214979e+293,  5.64211269e+294,  1.99890519e+294, ...,
        6.32941326e+294, -1.35253307e+293,  2.26298837e+294])

In [57]:
len(optimized_predictions)

1459

In [82]:
final_pred_array = list()

for i in range(len(optimized_predictions)):
  final_pred_array = final_pred_array + list(np.array(optimized_predictions[i]).flatten())

len(final_pred_array)

1459

In [69]:
final_pred_array[0]

1.101794378371207e+183

In [54]:
np.array(optimized_predictions[0]).flatten()[0]

1.101794378371207e+183

In [43]:
A = np.squeeze(np.asarray(optimized_predictions))
A

array([matrix([[1.10179438e+183]]), matrix([[6.9363358e+183]]),
       matrix([[2.45742657e+183]]), ..., matrix([[7.78129368e+183]]),
       matrix([[-1.66278557e+182]]), matrix([[2.7820868e+183]])],
      dtype=object)

In [40]:
len(optimized_predictions)

1459

In [0]:
submission_df = pd.DataFrame(test_df['Id'],columns=['Id','SalePrice'])
submission_df["SalePrice"] = predictions
submission_df = submission_df[["Id","SalePrice"]]
submission_df.shape

(1459, 2)

In [0]:
submission_df.head()

Id      SalePrice
0  1461  160922.199273
1  1462  182981.812809
2  1463  192247.197875
3  1464  197403.604159
4  1465  172446.952194

In [0]:
submission_df.to_csv("ss_submission_lmMv6_2.csv", index = False)